export const SAVE_CATEGORIES = "SAVE_CATEGORIES";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
