export const SAVE_DAILY_MENU_ITEM = "SAVE_DAILY_MENU_ITEM";
export const ADD_DAILY_MENU_ITEM = "ADD_DAILY_MENU_ITEM";
export const UPDATE_DAILY_MENU_ITEM = "UPDATE_DAILY_MENU_ITEM";
export const REMOVE_DAILY_MENU_ITEM = "REMOVE_DAILY_MENU_ITEM";