export const SAVE_ORDER_ITEM = "SAVE_ORDER_ITEM";
export const SAVE_ORDER_ITEMS = "SAVE_ORDER_ITEMS";
export const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
export const UPDATE_ORDER_ITEM = "UPDATE_ORDER_ITEM";
export const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";