export const SAVE_PRODUCTS = "SAVE_PRODUCTS";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
